stages:
  - function: bloods_delta_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/bloods/Unioxf_medtestN_20210929.csv"
    output_path: "/ons/covserolink/lamots"

  - function: swab_delta_ETL
    run: False
    resource_path: "hdfs:///ons/covserolink/landing_zone/swabs/ONS_GL_Report_20210926_0000.csv"
    output_path: "/ons/covserolink/lamots"

  - function: survey_responses_version_2_ETL
    run: True
    resource_path: "hdfs:///ons/covserolink/landing_zone/responses_v2/ONSECRF5_Datafile_20210929.csv"
    output_path: "/ons/covserolink/lamots"

csv_output_path: "/home/cdsw/output"
