# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run.
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ main ]
  pull_request: # And on all Pull Requests

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8

      - name: Check package build
        run: |
          python -m pip install --upgrade pip
          pip install wheel==0.29.0
          python setup.py sdist bdist_wheel
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Setup spark
        run: |
          cd ../../ &&
          wget -q -O spark.tgz https://archive.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.6.tgz &&
          tar xzvf spark.tgz &&
          rm "spark.tgz" &&
          (cd spark-2.4.0-bin-hadoop2.6 &&
          export SPARK_HOME=`pwd` &&
          export PYTHONPATH=$(ZIPS=("$SPARK_HOME"/python/lib/*.zip); IFS=:; echo "${ZIPS[*]}"):$PYTHONPATH
          )

      - name: Install Python dependencies
        # Wheel is specific here because of conflicts on this Python version
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc==1.5
          pip install -e .[ci]

      - name: Run pytest
        run: |
          pytest -v
